/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as GastosFixosRouteImport } from './routes/gastos-fixos'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as TabelaDinamicaRouteImport } from './routes/tabela-dinamica'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as MesAnoMesRouteImport } from './routes/mes.$ano.$mes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const GastosFixosRoute = GastosFixosRouteImport.update({
  id: '/gastos-fixos',
  path: '/gastos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelaDinamicaRoute = TabelaDinamicaRouteImport.update({
  id: '/tabela-dinamica',
  path: '/tabela-dinamica',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MesAnoMesRoute = MesAnoMesRouteImport.update({
  id: '/mes/$ano/$mes',
  path: '/mes/$ano/$mes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/tabela-dinamica': typeof TabelaDinamicaRoute
  '/wishlist': typeof WishlistRoute
  '/mes/$ano/$mes': typeof MesAnoMesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/tabela-dinamica': typeof TabelaDinamicaRoute
  '/wishlist': typeof WishlistRoute
  '/mes/$ano/$mes': typeof MesAnoMesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/gastos-fixos': typeof GastosFixosRoute
  '/lancamentos': typeof LancamentosRoute
  '/login': typeof LoginRoute
  '/metas': typeof MetasRoute
  '/tabela-dinamica': typeof TabelaDinamicaRoute
  '/wishlist': typeof WishlistRoute
  '/mes/$ano/$mes': typeof MesAnoMesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/gastos-fixos'
    | '/lancamentos'
    | '/login'
    | '/metas'
    | '/tabela-dinamica'
    | '/wishlist'
    | '/mes/$ano/$mes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/gastos-fixos'
    | '/lancamentos'
    | '/login'
    | '/metas'
    | '/tabela-dinamica'
    | '/wishlist'
    | '/mes/$ano/$mes'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/gastos-fixos'
    | '/lancamentos'
    | '/login'
    | '/metas'
    | '/tabela-dinamica'
    | '/wishlist'
    | '/mes/$ano/$mes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  GastosFixosRoute: typeof GastosFixosRoute
  LancamentosRoute: typeof LancamentosRoute
  LoginRoute: typeof LoginRoute
  MetasRoute: typeof MetasRoute
  TabelaDinamicaRoute: typeof TabelaDinamicaRoute
  WishlistRoute: typeof WishlistRoute
  MesAnoMesRoute: typeof MesAnoMesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastos-fixos': {
      id: '/gastos-fixos'
      path: '/gastos-fixos'
      fullPath: '/gastos-fixos'
      preLoaderRoute: typeof GastosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela-dinamica': {
      id: '/tabela-dinamica'
      path: '/tabela-dinamica'
      fullPath: '/tabela-dinamica'
      preLoaderRoute: typeof TabelaDinamicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mes/$ano/$mes': {
      id: '/mes/$ano/$mes'
      path: '/mes/$ano/$mes'
      fullPath: '/mes/$ano/$mes'
      preLoaderRoute: typeof MesAnoMesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  GastosFixosRoute: GastosFixosRoute,
  LancamentosRoute: LancamentosRoute,
  LoginRoute: LoginRoute,
  MetasRoute: MetasRoute,
  TabelaDinamicaRoute: TabelaDinamicaRoute,
  WishlistRoute: WishlistRoute,
  MesAnoMesRoute: MesAnoMesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
