/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as LancamentosRouteImport } from './routes/lancamentos'
import { Route as MetasRouteImport } from './routes/metas'
import { Route as TabelaDinamicaRouteImport } from './routes/tabela-dinamica'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LancamentosRoute = LancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetasRoute = MetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelaDinamicaRoute = TabelaDinamicaRouteImport.update({
  id: '/tabela-dinamica',
  path: '/tabela-dinamica',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/lancamentos': typeof LancamentosRoute
  '/metas': typeof MetasRoute
  '/tabela-dinamica': typeof TabelaDinamicaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/lancamentos': typeof LancamentosRoute
  '/metas': typeof MetasRoute
  '/tabela-dinamica': typeof TabelaDinamicaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/lancamentos': typeof LancamentosRoute
  '/metas': typeof MetasRoute
  '/tabela-dinamica': typeof TabelaDinamicaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/configuracoes' | '/lancamentos' | '/metas' | '/tabela-dinamica'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes' | '/lancamentos' | '/metas' | '/tabela-dinamica'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/lancamentos'
    | '/metas'
    | '/tabela-dinamica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LancamentosRoute: typeof LancamentosRoute
  MetasRoute: typeof MetasRoute
  TabelaDinamicaRoute: typeof TabelaDinamicaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lancamentos': {
      id: '/lancamentos'
      path: '/lancamentos'
      fullPath: '/lancamentos'
      preLoaderRoute: typeof LancamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metas': {
      id: '/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof MetasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela-dinamica': {
      id: '/tabela-dinamica'
      path: '/tabela-dinamica'
      fullPath: '/tabela-dinamica'
      preLoaderRoute: typeof TabelaDinamicaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LancamentosRoute: LancamentosRoute,
  MetasRoute: MetasRoute,
  TabelaDinamicaRoute: TabelaDinamicaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
